seed: 0
output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
load_checkpoint: ""
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False
run_mode: 'train'

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'mixtral-8x7b'
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: false
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 1        # num of epoch intervals between each eval, 1 means eval on every epoch end.

# runner config
runner_config:
  epochs: 10
  batch_size: 1
  sink_mode: True
  sink_size: 1

# optimizer
optimizer:
  type: AdamW
  betas: [0.9, 0.95]
  eps: 1.e-8

# moe
moe_config:
  expert_num: 64 # 8
  capacity_factor: 2 # 1.1 # if capacity_factor <= 0 means dropless
  aux_loss_factor: 0.01 # 0.05
  num_experts_chosen: 8
  routing_policy: "TopkRouterV2"
  enable_sdrop: False # True
  router_dense_type: "float32"
  use_fused_ops_topkrouter: True # False
  group_wise_a2a: True # add

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 1.e-5
  lr_end: 1.e-6
  warmup_ratio: 0.03
  total_steps: -1 # -1 means it will load the total steps of the dataset

# dataset
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "/home/ma-user/modelarts/user-job-dir/wikitext/wiki131072.mindrecord"
    shuffle: True
  input_columns: ["input_ids"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 4
  repeat: 1
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset


# eval dataset
eval_dataset: &eval_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: False
  input_columns: ["input_ids"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: False
  repeat: 1
  numa_enable: False
  prefetch_size: 1
eval_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *eval_dataset

use_parallel: True
# parallel context config
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  enable_alltoall: True
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    optimizer_weight_shard_size: 8
    parallel_optimizer_threshold: 64
# default parallel of device num = 8 910A
parallel_config:
  data_parallel: 1
  model_parallel: 8
  expert_parallel: 16
  context_parallel: 16
  pipeline_stage: 1
  use_seq_parallel: True
  micro_batch_num: 1 # 16
  vocab_emb_dp: True
  gradient_aggregation_group: 4 # 4
# when model parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

# recompute config
recompute_config:
  recompute: False
  select_recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: False
  recompute_slice_activation: False

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMonitor
    prefix: "mixtral-8x7b"
    save_checkpoint_steps: 1000
    integrated_save: False
    async_save: False
  - type: ObsMonitor

# mindspore context init config

context:
  jit_config:
    jit_level: "O1"
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  max_call_depth: 10000
  max_device_memory: "58GB"
  save_graphs: True
  save_graphs_path: "./graph"
  device_id: 0
  ascend_config:
    parallel_speed_up_json_path: "./parallel_speed_up.json"

# model config
model:
  model_config:
    type: LlamaConfig
    batch_size: 1 # add for increase predict
    seq_length: 131072
    hidden_size: 8192 # 4096
    intermediate_size: 10240 # 14336
    theta: 1000000
    num_layers: 8
    num_heads: 64 # 32
    vocab_size: 32000
    multiple_of: 256
    n_kv_heads: 8
    qkv_concat: True
    rms_norm_eps: 1.0e-5
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 0
    ignore_token_id: -100
    hidden_dropout_prob: 0.0
    attention_dropout_prob: 0.0
    embed_dropout_prob: 0.0
    compute_dtype: "bfloat16" # "float16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float32" # "float16"
    rotary_dtype: "float32" # "float16"
    param_init_type: "float32" # "float16"
    use_past: False
    extend_method: "None" # support "None", "PI", "NTK"
    use_flash_attention: True
    use_ring_attention: False
    use_attn_mask_compression: True
    parallel_optimizer: True
    offset: 0
    checkpoint_name_or_path: ""
    repetition_penalty: 1
    max_decode_length: 512
    top_k: 3
    top_p: 1
    do_sample: False
  arch:
    type: MixtralForCausalLM

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '<unk>'
    type: LlamaTokenizer
    vocab_file: "/.../tokenizer.model"
  type: LlamaProcessor

# metric
metric:
  type: PerplexityMetric

# wrapper cell config
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 65535
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

eval_callbacks:
  - type: ObsMonitor

auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

profile: True
profile_start_step: 5
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256

# aicc
remote_save_url: "Please input obs url on AICC platform."
