seed: 0
output_dir: './output'  # path to save checkpoint/strategy
load_checkpoint: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
use_parallel: False
run_mode: 'predict'

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'internlm_7b'

# default parallel of device num = 8 for Atlas 800T A2
parallel_config:
  model_parallel: 8
  pipeline_stage: 1

# recompute config
recompute_config:
  recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

# mindspore context init config
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  max_device_memory: "59GB"
  device_id: 0

# parallel context config
parallel:
  full_batch: True
  enable_parallel_optimizer: False

# model config
model:
  model_config:
    type: InternLMConfig
    auto_register: internlm_model.InternLMConfig
    batch_size: 1 # add for increase predict
    seq_length: 2048
    hidden_size: 4096
    num_layers: 32
    num_heads: 32
    vocab_size: 103168
    multiple_of: 256
    rms_norm_eps: 1.0e-6
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 2
    ignore_token_id: -100
    compute_dtype: "float16"
    layernorm_compute_type: "float16"
    softmax_compute_type: "float16"
    rotary_dtype: "float16"
    param_init_type: "float16"
    has_bias: True
    use_past: True
    use_flash_attention: True
    block_size: 16
    num_blocks: 512
    is_dynamic: True
    scaling_factor: 1.0
    extend_method: "None"
    offset: 0
    checkpoint_name_or_path: "internlm_7b"
    repetition_penalty: 1.0
    max_decode_length: 512
    top_k: 3
    top_p: 0.8
    do_sample: False
    auto_map:
      AutoModel: internlm.InternLMForCausalLM
      AutoConfig: internlm_config.InternLMConfig
      AutoTokenizer: [internlm_tokenizer.InternLMTokenizer, null]
  arch:
    type: InternLMForCausalLM
    auto_register: internlm_model.InternLMForCausalLM


processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '</s>'
    type: InternLMTokenizer
    auto_register: internlm_tokenizer.InternLMTokenizer
    vocab_file: './internlm-7b-chat/tokenizer.model'
  type: LlamaProcessor

# metric
metric:
  type: PerplexityMetric