seed: 0
run_mode: 'predict'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# ==== context config ====
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  max_call_depth: 10000
  max_device_memory: "59GB" # 59GB for Atlas 800T A2
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0
  memory_optimize_level: "O1"

# aicc
remote_save_url: "Please input obs url on AICC platform."

# ==== model config ====
model:
  model_config:
    type: YiZhaoConfig
    batch_size: 1  # only for incremental infer
    num_layers: 54
    padded_vocab_size: 151552
    hidden_size: 4096
    ffn_hidden_size: 13696
    kv_channels: 128
    num_attention_heads: 32
    seq_length: 8192
    hidden_dropout: 0.0
    attention_dropout: 0.0
    layernorm_epsilon: 1.e-05
    rope_ratio: 1
    rmsnorm: True
    apply_residual_connection_post_layernorm: False
    post_layer_norm: True
    add_bias_linear: False
    add_qkv_bias: True
    bias_dropout_fusion: True
    multi_query_attention: True
    multi_query_group_num: 2
    apply_query_key_layer_scaling: True
    attention_softmax_in_fp32: True
    fp32_residual_connection: False
    quantization_bit: 0
    pre_seq_len: None
    prefix_projection: False
    param_init_type: "bfloat16"
    compute_dtype: "bfloat16"
    layernorm_compute_type: "float32"
    rotary_dtype: "float32"
    use_past: True
    is_dynamic: True
    block_size: 16
    num_blocks: 4096
    use_flash_attention: True # when use FlashAttention, seq_length should be multiple of 16
    eos_token_id: [151329,151336]
    pad_token_id: 151329
    repetition_penalty: 1.0
    max_length: 8192
    max_decode_length: 8192
    checkpoint_name_or_path: ""
    top_k: 1
    top_p: 1
    do_sample: False
    qkv_concat: False
    mlp_concat: False
    use_llama_rope: True
    lm_head_dp: False
    pp_interleave_num: 1
    use_rearrange_rope: True
    auto_map:
      AutoTokenizer: [ yizhao_tokenizer.YiZhaoTokenizer, null ]

  arch:
    type: YiZhaoForCausalLM

trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'YiZhao'
# if True do, evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: 500
eval_epoch_interval: -1

metric:
  type: ADGENMetric

processor:
  return_tensors: ms
  tokenizer:
    type: YiZhaoTokenizer
    eos_token: '<|endoftext|>'
    pad_token: '<|endoftext|>'
    vocab_file: '/opt/wht/ckpt_dataset/glm4/tokenizer.model'
  type: YiZhaoProcessor

# parallel config
use_parallel: False
parallel:
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False  # 默认为False, 数据并行模式下为True
  loss_repeated_mean: True
  enable_alltoall: False
  full_batch: True   # 默认为True, 数据并行模式必须设置为False
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False  # optimizer shard, 等价于zero2
  strategy_ckpt_config:
    save_file: "./ckpt_strategy.ckpt"
parallel_config:
  data_parallel: 1
  model_parallel: 1
  pipeline_stage: 1
  expert_parallel: 1
  micro_batch_num: 16
  vocab_emb_dp: True
  use_seq_parallel: False
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# recompute
recompute_config:
  recompute: True
  select_recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 5
profile_stop_step: 7
init_start_profile: True
profile_communication: True
profile_memory: True

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMonitor
    prefix: "Yizhao"
    save_checkpoint_steps: 1000
    keep_checkpoint_max: 1
    integrated_save: False
    async_save: False
  - type: ObsMonitor
    keep_last: False
eval_callbacks:
  - type: ObsMonitor
    keep_last: False

# ==== runner config ====
runner_config:
  epochs: 1
  batch_size: 8
  sink_mode: True
  sink_size: 4
