llama:
  input_path:
  output_path:
  dtype:
  model_class: LlamaForCausalLM

glm:
  input_path:
  output_path:
  dtype:
  model_class: AutoModel

qwen:
  input_path:
  output_path:
  dtype:
  model_class: AutoModelForCausalLM

internlm:
  input_path:
  output_path:
  dtype:
  model_class: AutoModelForCausalLM

baichuan:
  input_path:
  output_path:
  dtype:
  model_class: AutoModelForCausalLM

gpt:
  input_path:
  output_path:
  dtype:
  layers:

blip:
  input_path:
  output_path:
  dtype:

glm2:
  input_path:
  output_path:
  dtype:
  model_class: AutoModel

mae:
  input_path:
  output_path:
  dtype:

vit:
  input_path:
  output_path:
  dtype:

swin:
  input_path:
  output_path:
  dtype:

knowlm:
  input_path:
  output_path:
  dtype:
  model_class: LlamaForCausalLM